TPM-Owned: Allow re-trying TPM owner password
If the wrong owner password was provided, allow additional attempts.

This could start hitting the TPM brute force protection, but it's
friendlier than requiring a reboot.

OXT-1130

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

diff --git a/part2/stages/TPM-Owned b/part2/stages/TPM-Owned
--- a/part2/stages/TPM-Owned
+++ b/part2/stages/TPM-Owned
@@ -32,7 +32,9 @@ if [ "${MEASURE_LAUNCH}" = "true" ]; then
              "system BIOS administrative interface." >&2
         exit ${Abort}
     else
-        dialog --colors --yes-label "Reboot" --no-label "Continue" --yesno "
+        dialog --colors --extra-button \
+        --extra-label "Retry" \
+        --yes-label "Reboot" --no-label "Continue" --yesno "
  The TPM in your platform is already owned.
 
  ${PRODUCT_BRAND} Measured Launch requires sole
@@ -44,6 +46,11 @@ if [ "${MEASURE_LAUNCH}" = "true" ]; then
  with ${PRODUCT_BRAND} Measured Launch disabled." 14 49
         case $? in
             1) exit ${Continue} ;;
+            3) # User pressed Retry
+               . /usr/lib/openxt/key-functions
+               remove_own_key
+               exit ${Retry}
+               ;;
             255) exit ${Previous} ;;
             *) exit ${Abort} ;;
         esac
