install-main: Re-use owned TPM with password
If the TPM is owned, and we know the password, we don't need to fail the
installation.

Depends on tpm_check_owner_password in tpm-functions.

OXT-1130

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

diff --git a/part2/stages/Functions/install-main b/part2/stages/Functions/install-main
--- a/part2/stages/Functions/install-main
+++ b/part2/stages/Functions/install-main
@@ -922,16 +922,14 @@ own_tpm()
         return 1
     fi
 
-    if [ "${TPM_OWNED}" = "true" ]; then
-        echo "TPM is owned, cannot own_tpm" >&2
-        return 1
-    fi
-
     local own_key=$(get_own_key)
-    tpm_take_ownership  "${own_key}" "${TPM_EK}"
-    if [ $? -ne 0 ]; then
-        echo "taking tpm ownership failed" >&2
-        return 1
+
+    if [ "${TPM_OWNED}" = "false" ]; then
+        tpm_take_ownership  "${own_key}" "${TPM_EK}"
+        if [ $? -ne 0 ]; then
+            echo "taking tpm ownership failed" >&2
+            return 1
+        fi
     fi
 
     generate_policy "${own_key}"
diff --git a/part2/stages/TPM-Check b/part2/stages/TPM-Check
--- a/part2/stages/TPM-Check
+++ b/part2/stages/TPM-Check
@@ -122,7 +122,7 @@ esac
 
 # Determine if the TPM has an EK
 tpm_has_ek
-case $? in 
+case $? in
     0)  TPM_EK='true' ;;
     1)  TPM_EK='false' ;;
     2)  echo "can't tell if TPM has an EK?" >&2
@@ -140,7 +140,6 @@ case $? in
         # password dialog etc
         TPM_OWNED='true'
         TPM_SRK='true'
-        exit ${TpmOwned}
         ;;
     1)  TPM_OWNED='false'
         TPM_SRK='false'
@@ -168,6 +167,21 @@ case $? in
         exit ${Abort}
         ;;
 esac
+
+[ "${TPM_OWNED}" = "true" ] && {
+    tpm_check_owner_password "$(get_own_key)"
+    case $? in
+        0)  ;;
+        1)  exit ${TpmOwned}
+            ;;
+        2)  echo "can't tell if we know owner password" >&2
+            exit ${Abort}
+            ;;
+        *)  echo "tpm_check_owner_password: This shouldn't happen!" >&2
+            exit ${Abort}
+            ;;
+    esac
+}
 
 TPM_GAUGE=$((${TPM_GAUGE}+${TPM_GAUGE_STEP}))
 update_gauge "${CHECK_MSG}" ${TPM_GAUGE}
