Create ESP and install on UEFI

diff --git a/part2/stages/Functions/install-main b/part2/stages/Functions/install-main
--- a/part2/stages/Functions/install-main
+++ b/part2/stages/Functions/install-main
@@ -388,6 +388,11 @@ commit_dom0()
 
     do_cmd mkdir -p ${DOM0_MOUNT}/storage/disks || return 1
 
+    copy_to_esp
+    if [ $? -eq 1 ]; then
+        return 1
+    fi
+
     install_bootloader_from_dom0fs || return 1
 
     mixedgauge "Taking ownership of TPM" 50
@@ -528,6 +533,95 @@ install_bootloader_from_dom0fs()
         echo "Error installing the bootloader">&2
         return 1
     }
+    return 0
+}
+
+create_efi_boot_entries()
+{
+    local DISK_DEV="/dev/${TARGET_DISK}"
+
+    do_cmd efibootmgr -w -L "OpenXT (safe graphics)" -l "\EFI\BOOT\BOOTX64.EFI" -c -d ${DISK_DEV} --part 1 -u "openxt-support-safe-graphics" >&2
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry" >&2
+        return 1
+    fi
+
+    do_cmd efibootmgr -w -L "OpenXT (AMT)" -l "\EFI\BOOT\BOOTX64.EFI" -c -d ${DISK_DEV} --part 1 -u "openxt-support-amt" >&2
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry" >&2
+        return 1
+    fi
+
+    do_cmd efibootmgr -w -L "OpenXT (console)" -l "\EFI\BOOT\BOOTX64.EFI" -c -d ${DISK_DEV} --part 1 -u "openxt-support-console" >&2
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry" >&2
+        return 1
+    fi
+
+    do_cmd efibootmgr -w -L "OpenXT (console AMT)" -l "\EFI\BOOT\BOOTX64.EFI" -c -d ${DISK_DEV} --part 1 -u "openxt-support-console-amt" >&2
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry" >&2
+        return 1
+    fi
+
+    do_cmd efibootmgr -w -L "OpenXT" -l "\EFI\BOOT\BOOTX64.EFI" -c -d ${DISK_DEV} --part 1 >&2
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry" >&2
+        return 1
+    fi
+
+
+    # Remove duplicate entries (if any)
+    do_cmd efibootmgr -D >&2
+
+    return 0
+}
+
+copy_to_esp()
+{
+    local ESP=$(sfdisk -l -q | grep "EFI System" | awk '{ print $1 }')
+    if [ "${ESP}" == "" ]; then
+        echo "No EFI System Partition on disk ${DISK_DEV}" >&2
+        if [ -d /sys/firmware/efi/efivars ]; then
+            return 1
+        else
+            return 0
+        fi
+    fi
+
+    do_mount ${ESP} ${ESP_MOUNT} >&2
+    if [ "$?" != "0" ]; then
+        echo "Couldn't mount ${ESP}, already mounted?" >&2
+        return 1
+    fi
+
+    do_cmd mkdir -p ${ESP_MOUNT}/EFI/BOOT >&2
+    do_cmd cp -f ${DOM0_MOUNT}/boot/xen.efi \
+          ${DOM0_MOUNT}/boot/shimx64.efi \
+          ${DOM0_MOUNT}/boot/bzImage \
+          ${DOM0_MOUNT}/boot/initramfs.gz \
+          ${DOM0_MOUNT}/boot/microcode_intel.bin \
+          ${DOM0_MOUNT}/etc/xen/xenrefpolicy/policy/policy.24 \
+          ${DOM0_MOUNT}/usr/share/xenclient/bootloader/openxt.cfg \
+          ${ESP_MOUNT}/EFI/BOOT >&2
+
+    if [ "$?" != "0" ]; then
+        echo "Failed to copy files to ESP" >&2
+        do_cmd umount ${ESP_MOUNT}
+        return 1
+    fi
+    # Copy the shim to the EFI removable path to work around buggy firmwares
+    do_cmd cp -f ${ESP_MOUNT}/EFI/BOOT/shimx64.efi \
+          ${ESP_MOUNT}/EFI/BOOT/BOOTX64.EFI >&2
+    do_cmd sync >&2
+
+    do_cmd umount ${ESP_MOUNT} >&2
+
+    if [ -d /sys/firmware/efi/efivars ]; then
+        create_efi_boot_entries
+        return $?
+    fi
+
     return 0
 }
 
diff --git a/part2/stages/Make-ESP-partition b/part2/stages/Make-ESP-partition
--- a/part2/stages/Make-ESP-partition
+++ b/part2/stages/Make-ESP-partition
@@ -22,33 +22,41 @@
 . ${PARTITION_CONF}
 . ${SCRIPT_DIR}/Functions/install-main
 
-# GRUB Stage 1.5 lives in the BIOS Boot Partition
-# GRUB2 will automatically find this partition when grub is installed
-create_bios_boot_partition()
+create_efi_system_partition()
 {
     local PARTITION="${XC_PARTITION}"
     local DISK=$(get_partition_disk "${PARTITION}")
     local DISK_DEV="/dev/${DISK}"
 
-    local BBP_PARTNUM="2"
-    local BBP_SIZE="+1M"  # 1 MiB
-    local BBP_TYPE="EF02" # BIOS Boot Partition Typecode
+    local EFI_SYSTEM_PARTITION_GUID="C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
+    local ESP=$(sfdisk -d ${DISK_DEV} | grep "type=${EFI_SYSTEM_PARTITION_GUID}" | awk '{ print $1 }')
+    local ESP_PARTNUM="1"
+    local ESP_SIZE="+100M"  # 1 MiB
+    local ESP_TYPE="EF00" # EFI System Partition Typecode
 
-	if do_cmd sgdisk -p "${DISK_DEV}" | grep -i ${BBP_TYPE} >&2 ; then
-		echo "BBP already exists, continue." >&2
-		return 0
-	fi
+    if [ "${ESP}" != "" ]; then
+        echo "ESP already exists, continue." >&2
+        return 0
+    fi
 
-	echo "No BBP detected, attempting to create a BBP." >&2
-    # Create the BBP
-    if ! do_cmd sgdisk -g -n ${BBP_PARTNUM}::${BBP_SIZE} -t ${BBP_PARTNUM}:${BBP_TYPE} "${DISK_DEV}" >&2 ; then
-        echo "ERROR: Could not create BIOS Boot Partition." >&2
+    echo "No ESP detected, attempting to create a ESP." >&2
+
+    # Create the ESP
+    if ! do_cmd sgdisk -g -n ${ESP_PARTNUM}::${ESP_SIZE} -t ${ESP_PARTNUM}:${ESP_TYPE} "${DISK_DEV}" >&2 ; then
+        echo "ERROR: Could not create EFI System Partition." >&2
+        return 1
+    fi
+
+    ESP=$(sfdisk -d ${DISK_DEV} | grep "type=${EFI_SYSTEM_PARTITION_GUID}" | awk '{ print $1 }')
+
+    if ! do_cmd mkfs.vfat -F 32 "${ESP}" >&2 ; then
+        echo "ERROR: Could not format ESP at '${ESP}' as FAT32" >&2
         return 1
     fi
 
     return 0
 }
 
-create_bios_boot_partition || exit ${Abort}
+create_efi_system_partition || exit ${Abort}
 
 exit ${Continue}
diff --git a/part2/stages/TPM-Check b/part2/stages/TPM-Check
--- a/part2/stages/TPM-Check
+++ b/part2/stages/TPM-Check
@@ -25,6 +25,7 @@ if [ "${MEASURE_LAUNCH}" = "false" ]; then
 fi
 
 TPM_FUNCS=/usr/lib/tpm-scripts/tpm-functions
+KEY_FUNCS=/usr/lib/openxt/key-functions
 if [ ! -f ${TPM_FUNCS} ]; then
     echo "No tpm-function library found at ${TPM_FUNCS}.  ABORT" >&2
     exit ${Abort}
@@ -32,12 +33,21 @@ else
     . ${TPM_FUNCS}
 fi
 
-MLE_FUNCS=/usr/lib/openxt/ml-functions
-if [ ! -f ${MLE_FUNCS} ]; then
-    echo "No ml-function library found at ${MLE_FUNCS}.  ABORT" >&2
+if [ ! -f ${KEY_FUNCS} ]; then
+    echo "No key-functions library found at ${KEY_FUNCS}.  ABORT" >&2
     exit ${Abort}
 else
-    . ${MLE_FUNCS}
+    . ${KEY_FUNCS}
+fi
+
+if [ ! -d /sys/firmware/efi/efivars ]; then
+    MLE_FUNCS=/usr/lib/openxt/ml-functions
+    if [ ! -f ${MLE_FUNCS} ]; then
+        echo "No ml-function library found at ${MLE_FUNCS}.  ABORT" >&2
+        exit ${Abort}
+    else
+        . ${MLE_FUNCS}
+    fi
 fi
 
 CHECK_MSG="Checking availability of TXT & TPM."
@@ -218,9 +228,11 @@ TPM_GAUGE=$((${TPM_GAUGE}+${TPM_GAUGE_STEP}))
 update_gauge "${CHECK_MSG}" ${TPM_GAUGE}
 log_tpm_attrs || exit ${Abort}
 
-TPM_GAUGE=$((${TPM_GAUGE}+${TPM_GAUGE_STEP}))
-update_gauge "${CHECK_MSG}" ${TPM_GAUGE}
-mle_success || exit ${TxtFail}
+if [ ! -d /sys/firmware/efi/efivars ]; then
+    TPM_GAUGE=$((${TPM_GAUGE}+${TPM_GAUGE_STEP}))
+    update_gauge "${CHECK_MSG}" ${TPM_GAUGE}
+    mle_success || exit ${TxtFail}
+fi
 
 TPM_GAUGE=$((${TPM_GAUGE}+${TPM_GAUGE_STEP}))
 update_gauge "${CHECK_MSG}" ${TPM_GAUGE}
