TPM2 ownership
Check the ownership and reuse if we know the password.  We also take
care to re-create the TPM2 objects handles if necessary.

OXT-1130

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

diff --git a/part2/stages/Functions/install-main b/part2/stages/Functions/install-main
--- a/part2/stages/Functions/install-main
+++ b/part2/stages/Functions/install-main
@@ -923,8 +923,7 @@ is_mounted()
 }
 
 # take ownership of TPM if necessary
-own_tpm()
-{
+own_tpm() {
     if [ "${TPM_STATE}" != "active" ]; then
         echo "TPM sate not active, canot own_tpm" >&2
         return 1
@@ -938,6 +937,15 @@ own_tpm()
             echo "taking tpm ownership failed" >&2
             return 1
         fi
+    fi
+
+    if ! tpm_handles_defined; then
+        local err
+
+        err=$( tpm_create_handles "${own_key}" ) || {
+            echo "error creating TPM handles: ${err}" >&2
+            return 1
+        }
     fi
 
     generate_policy "${own_key}"
